### ISSUE TITLE
tests: pymssql (sql output dependency) installation fails

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2539]
tests (pytest full) on Python 3.7 and 3.8 fails with:

```
+ pip install -r intelmq/bots/outputs/sql/REQUIREMENTS.txt
intelmq/bots/outputs/sql/REQUIREMENTS.txt
Requirement already satisfied: psycopg2-binary>=2.5.5 in /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages (from -r intelmq/bots/outputs/sql/REQUIREMENTS.txt (line 4)) (2.9.9)
Collecting pymssql>=2.2 (from -r intelmq/bots/outputs/sql/REQUIREMENTS.txt (line 5))
  Downloading pymssql-2.3.2.tar.gz (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.8/184.8 kB 8.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml): started
  Building wheel for pymssql (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      prefix='/usr/local'
      setup.py: platform.system() => Linux
      setup.py: platform.architecture() => ('64bit', 'ELF')
      setup.py: platform.libc_ver() => ('glibc', '2.34')
      setup.py: include_dirs => ['/usr/local/include']
      setup.py: library_dirs => ['/usr/local/lib']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/pymssql
      copying src/pymssql/exceptions.py -> build/lib.linux-x86_64-cpython-37/pymssql
      copying src/pymssql/__init__.py -> build/lib.linux-x86_64-cpython-37/pymssql
      running build_ext
      Compiling src/pymssql/_mssql.pyx because it changed.
      [1/1] Cythonizing src/pymssql/_mssql.pyx
      building 'pymssql._mssql' extension
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/src
      creating build/temp.linux-x86_64-cpython-37/src/pymssql
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/opt/hostedtoolcache/Python/3.7.17/x64/include/python3.7m -c src/pymssql/_mssql.c -o build/temp.linux-x86_64-cpython-37/src/pymssql/_mssql.o -DMSDBLIB
      src/pymssql/_mssql.c:1275:10: fatal error: sqlfront.h: No such file or directory
       1275 | #include "sqlfront.h"
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
Failed to build pymssql

Notice:  A new release of pip is available: 23.0.1 -> 24.0
Notice:  To update, run: pip install --upgrade pip
```

It works on 3.9 and newer. Disabling the sql output bot tests on the two older versions may be an option

**Comment by KasperSaederup** [comment]
still fails after pip upgrade: Collecting pymssql
  Using cached pymssql-2.3.4.tar.gz (184 kB)
src/pymssql/_mssql.pyx:858:19: undeclared name not builtin: long
